---
# Setup
- name: Add {{ app_name }} user
  ansible.builtin.user:
    name: "{{ app_name }}"
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ app_name }}"
    groups: docker
    append: true

- name: Add app directories
  ansible.builtin.file:
    path: "{{ app_folder }}/{{ item }}"
    mode: 0644
    owner: "{{ app_name }}"
    state: directory
  loop:
  - "database"
  - "data"

# Application
- name: Add docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ app_folder }}/docker-compose.yml"
    mode: 0644

- name: Start Docker Compose Services
  community.docker.docker_compose:
    project_src: "{{ app_folder }}"
    state: present

# Backups
- name: Add directory backup
  ansible.builtin.include_role:
    name: usmanatron.backup_directory
  vars:
    parent_directory: "{{ app_folder }}"
    directory: data

- name: Add database backup
  ansible.builtin.include_role:
    name: usmanatron.backup_mariadb
  vars:
    parent_directory: "{{ app_folder }}"
    database_name: "{{ app_name }}"
    database_username: "{{ monica_database_username }}"
    database_password: "{{ monica_database_password }}"